name: Gradle

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Check with Gradle
        run: ./gradlew check
      - name: Integration Test with Gradle
        run: ./gradlew integrationTest
      - uses: codecov/codecov-action@v1.5.2
